name: GithubActionsTest

on:
  push:
    branches: ["prod"]

jobs:
  pull-prod:
    runs-on: self-hosted
    steps:
      - name: Pull Latest Change
        run: cd /var/www/wordpress && git pull origin prod